In [41]:
import glam
import pandas as pd
import numpy as np
import os.path

import matplotlib.pyplot as plt
from analysis_functions import make_sure_path_exists

In [42]:
df = pd.read_csv('data/FF2018_data/GlamDataFF2018_Like_Bin_v2.csv') 

In [43]:
df.head()

Unnamed: 0  subject  trial    rt  choice  item_value_0  item_value_1  \
0           0        0      0  2009       0           0.0           0.0   
1           1        0      1  3371       0           5.0           4.0   
2           2        0      2  1700       1           0.0           5.0   
3           3        0      3  7466       1           1.0           2.0   
4           4        0      4  1889       1           5.0           5.0   

     gaze_0    gaze_1  
0  0.568396  0.431604  
1  0.762332  0.237668  
2  0.446809  0.553191  
3  0.532352  0.467648  
4  0.529736  0.470264

In [44]:
gaze_cols = ([col for col in df.columns
                  if col.startswith('gaze_')])
n_items = len(gaze_cols)

In [45]:
gaze = df[gaze_cols].values
left_gaze_advantage_raw = gaze[:, 0] - np.mean(gaze[:, 1:], axis=1)

df['left_gaze_advantage_raw'] = left_gaze_advantage_raw


In [46]:
left_gaze_advantage_raw

array([ 0.13679245,  0.52466368, -0.10638298, ...,  0.0195003 ,
       -0.23476209, -0.0351706 ])

In [30]:
bins = pd.qcut(left_gaze_advantage_raw, 8,labels=False)
bins

array([5, 7, 2, ..., 4, 1, 3])

In [32]:
np.unique(bins)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
df['left_gaze_advantage_bins'] = bins


In [64]:
df['left_gaze_advantage_bins'].value_counts()

7    495
5    495
3    495
1    495
6    495
4    495
2    495
0    495
Name: left_gaze_advantage_bins, dtype: int64

## First attempt to bin gaze difference (left_gaze_advantage) by participant using z-score

In [60]:
bins_values = []
for i in (df['subject'].unique()):
    Choicedata_gaze = df.loc[df['subject'] == i]
    bins_per_subj = pd.qcut(Choicedata_gaze['left_gaze_advantage_raw'], 8,labels=False)
    for  j in range(len(bins_per_subj)):    
        bins_values.append(bins_per_subj.values[j])
df['left_gaze_advantage_bins'] = bins_values


In [63]:
df

Unnamed: 0  subject  trial    rt  choice  item_value_0  item_value_1  \
0              0        0      0  2009       0           0.0           0.0   
1              1        0      1  3371       0           5.0           4.0   
2              2        0      2  1700       1           0.0           5.0   
3              3        0      3  7466       1           1.0           2.0   
4              4        0      4  1889       1           5.0           5.0   
5              5        0      5  2227       1           4.0           4.0   
6              6        0      6  4259       0           4.0           0.0   
7              7        0      7  3505       0           3.0           0.0   
8              8        0      8  2548       0           3.0           0.0   
9              9        0      9  3226       1           0.0           5.0   
10            10        0     10  4604       0           4.0           0.0   
11            11        0     11  6333       0           0.0           5.0   
12            12        0     12  5716       0           0.0           0.0   
13            13        0     13  3562       0           5.0           0.0   
14            14        0     14  2447       0           4.0           0.0   
15            15        0     15  2120       1           1.0           4.0   
16            16        0     16  6932       1           5.0           5.0   
17            17        0     17  4274       1           1.0           4.0   
18            18        0     18  6854       0           4.0           2.0   
19            19        0     19  6698       0           0.0           0.0   
20            20        0     20  2913       0           0.0           0.0   
21            21        0     21  4513       0           4.0           3.0   
22            22        0     22  2110       1           4.0           5.0   
23            23        0     23  3385       0           4.0           2.0   
24            24        0     24  2456       1           2.0           5.0   
25            25        0     25  2136       0           4.0           4.0   
26            26        0     26  7010       1           0.0           3.0   
27            27        0     27  4784       0           0.0           0.0   
28            28        0     28  2697       1           0.0           3.0   
29            29        0     29  4654       1           1.0           3.0   
...          ...      ...    ...   ...     ...           ...           ...   
3930        3930       32     90  2713       0           3.0           4.0   
3931        3931       32     91  2609       1           2.0           4.0   
3932        3932       32     92  2694       0           3.0           3.0   
3933        3933       32     93  2761       1           2.0           3.0   
3934        3934       32     94  2285       1           3.0           1.0   
3935        3935       32     95  1613       0           2.0           1.0   
3936        3936       32     96  2841       1           1.0           2.0   
3937        3937       32     97  2258       0           1.0           3.0   
3938        3938       32     98  1243       1           1.0           4.0   
3939        3939       32     99  1767       0           3.0           1.0   
3940        3940       32    100  2423       1           4.0           2.0   
3941        3941       32    101  1217       0           3.0           3.0   
3942        3942       32    102  3420       1           4.0           3.0   
3943        3943       32    103  8198       0           1.0           4.0   
3944        3944       32    104  5417       1           3.0           4.0   
3945        3945       32    105  1100       1           1.0           2.0   
3946        3946       32    106  1789       0           4.0           1.0   
3947        3947       32    107  4438       1           3.0           3.0   
3948        3948       32    108  3252       1           3.0           3.0   
3949        3949       32   

In [ ]:
z_matrix_values = []
for i in (df['subject'].unique()):
    Choicedata_ddm = df.loc[df['parcode'] == i]
    
    pX_LV =  pd.to_numeric(Choicedata_ddm["item_left"]) 
    meanLV = np.mean(pX_LV)
    stdLV =  np.std(pX_LV)
    p_zLV = (pX_LV - meanLV)/stdLV
     
    # We generate bins using the z-scored values.
    # We consider 6 levels
    # 1 . -inf < x <  -2*std
    # 2 . -2*std <= x <  -std
    # 3 . -std <= x <  0
    # 4 . 0 <= x <  std
    # 5 . std <= x <  2*std
    # 6 . 2*std <= x <  inf
    
    binLV =  -1
    p_binLV = []
    
    
    # Avoid the problem of indexing
    p_zLV = p_zLV.reset_index()    
    p_zLV = p_zLV.drop(['index'], 1)
    p_zLV = p_zLV["item_left"]

    # 6 bins for the value
    for  j in range(len(p_zLV)):  
        # bin the value of the left item 
        if p_zLV[j] < (-2*stdLV):
            binLV = 0
        elif -2*stdLV <= p_zLV[j] and p_zLV[j]< -stdLV:
            binLV = 1
        elif -stdLV <= p_zLV[j] and p_zLV[j]< 0:
            binLV = 2
        elif 0 <= p_zLV[j] and p_zLV[j]< stdLV:
            binLV = 3
        elif stdLV <= p_zLV[j] and p_zLV[j]< 2*stdLV:
            binLV = 4
        elif 2*stdLV <=p_zLV[j]:
            binLV = 5
        
        # bin the value of the left item 
        if p_zRV[j] < -2*stdRV:
            binRV = 0
        elif -2*stdRV <= p_zRV[j] and p_zRV[j]< -stdRV:
            binRV = 1
        elif -stdRV <= p_zRV[j] and p_zRV[j]< 0:
            binRV = 2
        elif 0 <= p_zRV[j] and p_zRV[j]< stdRV:
            binRV = 3
        elif stdRV <= p_zRV[j] and p_zRV[j]< 2*stdRV:
            binRV = 4
        elif 2*stdRV < p_zRV[j]:
            binRV = 5
        
        p_binLV.append(binLV)
        p_binRV.append(binRV)
    
    z_matrix_aux= np.column_stack((p_zLV,p_zRV,p_binLV,p_binRV))
    
    for  j in range(len(z_matrix_aux)):    
        z_matrix_values.append(z_matrix_aux[j])

In [ ]:
def add_left_gaze_advantage(df):
    """
    Compute gaze advantage of left item and add to DataFrame.

    Left relative gaze – mean other relative gaze
    In the binary case, this reduces to g0 - g1.

    Parameters
    ----------
    df :      <pandas DataFrame>
              Trial wise DataFrame containing columns for gaze_i
    """

    # infer number of items
    gaze_cols = ([col for col in df.columns
                  if col.startswith('gaze_')])
    n_items = len(gaze_cols)

    gaze = df[gaze_cols].values
    left_gaze_advantage = gaze[:, 0] - np.mean(gaze[:, 1:], axis=1)

    df['left_gaze_advantage'] = left_gaze_advantage

    return df.copy()